# Generated by Django 5.0.6 on 2024-05-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleleiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.CreateModel(
            name='DadosCabeleleiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('anos_de_experiencia', models.IntegerField()),
                ('rg', models.ImageField(upload_to='rgs')),
                ('certificado_cabeleleiro', models.ImageField(upload_to='certificado')),
                ('foto', models.ImageField(upload_to='foto_perfil')),
                ('descricao', models.TextField()),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabeleleiro.especialidades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
