# Generated by Django 5.0.6 on 2024-05-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleleiro', '0002_alter_especialidades_options_dadoscabeleleiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCabelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCabelos', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cabelo',
                'verbose_name_plural': 'Cabelos',
            },
        ),
    ]
