# Generated by Django 5.0.6 on 2024-05-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleleiro', '0006_rename_anos_de_experiencia_dadoscabeleleiro_anosexp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadoscabeleleiro',
            old_name='anos_de_experiencia',
            new_name='anos_de_experiencia',
        ),
    ]
