# Generated by Django 5.0.6 on 2024-05-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleleiro', '0007_rename_anosexp_dadoscabeleleiro_anosexp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadoscabeleleiro',
            old_name='anos_de_experiencia',
            new_name='anos_de_experiencia',
        ),
    ]
