# Generated by Django 5.0.6 on 2024-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleleiro', '0009_datasabertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasabertas',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
